

### GCP Storage - - - - - - - - - - - - - - - - - - - - - -

PROJECT_NAME = 'star-project-296512'
BUCKET_NAME = 'data-475'
# os.getenv('MAPBOX_API_KEY')
BUCKET_TRAIN_DATA_PATH = 'data/jan'
LISTINGS_COLUMNS = ['id',
             'name',
             'summary',
             'space',
             'description',
             'experiences_offered',
             'neighborhood_overview',
             'notes',
             'transit',
             'access',
             'interaction',
             'house_rules',
             'host_since',
             'host_location',
             'host_about',
             'host_response_time',
             'host_response_rate',
             'host_neighbourhood',
             'host_listings_count',
             'host_total_listings_count',
             'host_verifications',
             'host_identity_verified',
             'street',
             'neighbourhood_cleansed',
             'zipcode',
             'latitude',
             'longitude',
             'is_location_exact',
             'property_type',
             'room_type',
             'accommodates',
             'bathrooms',
             'bedrooms',
             'beds',
             'bed_type',
             'amenities',
             'price',
             'weekly_price',
             'monthly_price',
             'security_deposit',
             'cleaning_fee',
             'guests_included',
             'extra_people',
             'minimum_nights',
             'maximum_nights',
             'availability_30',
             'availability_60',
             'availability_90',
             'availability_365',
             'number_of_reviews',
             'number_of_reviews_ltm',
             'first_review',
             'last_review',
             'review_scores_rating',
             'review_scores_accuracy',
             'review_scores_cleanliness',
             'review_scores_checkin',
             'review_scores_communication',
             'review_scores_location',
             'review_scores_value',
             'instant_bookable',
             'cancellation_policy',
             'require_guest_profile_picture',
             'require_guest_phone_verification',
             'reviews_per_month']

KEY_AMENITIES = [['Free parking on premises', 'free street parking',
                  'paid parking on premises' ,'paid parking off premises'],
                'Dryer','Wifi','Breakfast',
                'Indoor fireplace',
                ['TV', 'cable tv'],
                ['Smoke alarm','Smoke detector']]

PRICES = [950760, 301518,667593,357779,578705,502623,1099876,399645,
         578110,463806,462820,614955,972231,683987,527206,387535,
         452272,507876,778290,2092485,573938,616126,475142,638519,
         409477,452437,819044,641210,402121,554009,459922,818443,1718124]

BOROUGHS = ['City of London', 'Barking and Dagenham', 'Barnet', 'Bexley','Brent', 'Bromley', 'Camden',
            'Croydon', 'Ealing', 'Enfield', 'Greenwich', 'Hackney', 'Hammersmith and Fulham', 'Haringey', 'Harrow',
            'Havering', 'Hillingdon', 'Hounslow', 'Islington', 'Kensington and Chelsea', 'Kingston upon Thames',
            'Lambeth', 'Lewisham', 'Merton', 'Newham', 'Redbridge', 'Richmond upon Thames', 'Southwark',
            'Sutton', 'Tower Hamlets', 'Waltham Forest', 'Wandsworth', 'Westminster']
